kibana_server_host: "0.0.0.0"
kibana_server_port: 5601
kibana_config_dir: "/etc/kibana"
kibana_config_path: "{{ kibana_config_dir }}/kibana.yml"
kibana_elasticsearch_url: "http://{{ hostvars['elastic01'].ip }}:9200"
