---

# - name: Check presence of fastestmirror.conf
#   stat:
#     path: /etc/yum/pluginconf.d/fastestmirror.conf
#   register: fastestmirror

# # fastestmirror plugin actually slows down Ansible deployments
# - name: Disable fastestmirror plugin
#   lineinfile:
#     dest: /etc/yum/pluginconf.d/fastestmirror.conf
#     regexp: "^enabled=.*"
#     line: "enabled=0"
#     state: present
#   when: fastestmirror.stat.exists

- name: Install updates
  package: name=* state=latest update_cache=yes

- name: Install packages requirements for bootstrap
  package:
    name:
      - libselinux-python
      - policycoreutils-python
      - initscripts
      - net-tools
      - httpd-tools
    state: present